instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('publications.urls', namespace='publications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/publications/urls.py
from django.urls import path
from .views import PostListView, PostDeleteView, PostEditView, PostDetailView, CommentCreateView, LikeView, \
    PostCreateView, CommentDeleteView

app_name = 'publications'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('posts/<int:post_pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:post_pk>/edit/', PostEditView.as_view(), name='post_edit'),
    path('posts/<int:post_pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/<int:post_pk>/comment/', CommentCreateView.as_view(), name='comment_create'),
    path('posts/<int:post_pk>/like/', LikeView.as_view(), name='like'),
    path('posts/new/', PostCreateView.as_view(), name='post_create'),
    path('comments/<int:comment_pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

instagram/users/urls.py
from django.urls import path
from .views import UserDetailView, UserEditView, UserSubscribeView, UserPasswordChangeView, UserLogoutView, \
    account_register_view, account_login_view


app_name = 'users'

urlpatterns = [
    path('<int:user_pk>/', UserDetailView.as_view(), name='details'),
    path('<int:user_pk>/edit/', UserEditView.as_view(), name='edit'),
    path('<int:user_pk>/subscribe/', UserSubscribeView.as_view(), name='subscribe'),
    path('<int:user_pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', account_register_view, name='register'),
    path('login/', account_login_view, name='login'),
]

instagram/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to='user_pics',
        verbose_name='Аватар'
    )
    description = models.TextField(
        null=True,
        blank=True,
        max_length=500,
        verbose_name='Дополнительная информация',
        default=None
    )
    phone = models.CharField(
        null=True,
        blank=True,
        max_length=100,
        verbose_name='Номер телефона',
        default=None
    )
    gender = models.CharField(
        null=True,
        blank=True,
        verbose_name='Пол',
        max_length=100,
        default=None
    )
    status = models.CharField(
        null=True,
        blank=True,
        verbose_name='Статус',
        default=None,
        max_length=100
    )

    def __str__(self):
        return self.username


class Subscription(models.Model):
    subscriber = models.ForeignKey(
        'users.User',
        related_name='subscriptions',
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        null=False,
        blank=False,
        default=None
    )
    subscribed_to = models.ForeignKey(
        'users.User',
        related_name='subscribers',
        on_delete=models.CASCADE,
        verbose_name='Подписан на',
        null=False,
        blank=False,
        default=None
    )

    def __str__(self):
        return f'{self.subscriber.username} подписан на {self.subscribed_to.username}'

instagram/users/forms.py
from django import forms

from .models import User


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'avatar',
            'description',
            'status',
            # 'gender',
            'phone'
        ]
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Электронная почта',
            'avatar': 'Аватар',
            'description': 'Информация',
            'status': 'Статус',
            # 'gender': 'Пол',
            'phone': 'Телефон',
        }


class UserPasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", strip=False, widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неверен')
        return old_password

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if self.instance.check_password(password):
            raise forms.ValidationError('Новый пароль совпадает со старым')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают')
        return password_confirm

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['old_password', 'password', 'password_confirm']
        labels = {
            'old_password': 'Старый пароль',
            'password': 'Пароль',
            'password_confirm': 'Подтверждение пароля',
        }


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвердите пароль', strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают')
        return password_confirm

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']
        labels = {
            'username': 'Логин',
            'password': 'Пароль',
            'password_confirm': 'Подтверждение пароля',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Электронная почта',
        }


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', strip=False, widget=forms.PasswordInput)

    def clean(self):
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            raise forms.ValidationError('Неверное имя пользователя')
        return username

    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = User.objects.get(username=username)

        if not user.check_password(password):
            raise forms.ValidationError('Неверный пароль')
        return password

    class Meta:
        model = User
        fields = ['username', 'password']
        labels = {
            'username': 'Логин',
            'password': 'Пароль',
        }

instagram/users/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, redirect
from django.views.generic import *
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.apps import apps

from .models import User
from .forms import *


class UserDetailView(DetailView):
    template_name = 'user/details.html'
    pk_url_kwarg = 'user_pk'
    model = User
    context_object_name = 'account'

    def get_context_data(self, **kwargs):
        Post = apps.get_model('publications', 'Post')
        posts = Post.objects.filter(author__pk=self.kwargs.get('user_pk'))
        kwargs['posts'] = posts
        kwargs['posts_count'] = len(posts)
        return super().get_context_data(**kwargs)


class UserEditView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user/edit.html'
    form_class = UserEditForm
    context_object_name = 'account'
    pk_url_kwarg = 'user_pk'

    def test_func(self):
        return self.request.user.pk == self.kwargs['user_pk']

    def get_success_url(self):
        return reverse('users:details', kwargs={'user_pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user/password_change.html'
    form_class = UserPasswordChangeForm
    context_object_name = 'account'
    pk_url_kwarg = 'user_pk'

    def test_func(self):
        return self.request.user.pk == self.kwargs['user_pk']

    def get_success_url(self):
        return reverse('users:login')


class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(request.META.get('HTTP_REFERER'))


def account_login_view(request):
    if request.method == 'POST':
        context = {
            'form': UserLoginForm(data=request.POST)
        }
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('publications:post_list')
        else:
            context['has_error'] = True
            return render(request, 'user/login.html', context=context)
    context = {
        'form': UserLoginForm()
    }
    return render(request, 'user/login.html', context=context)


def account_register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('publications:post_list')
        else:
            context = {
                'form': form,
                'has_error': True
            }
            return render(request, 'user/register.html', context=context)
    else:
        form = UserRegisterForm()
        context = {
            'form': form
        }
        return render(request, 'user/register.html', context=context)

instagram/users/views/subscription_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic import View

from ..models import User, Subscription


class UserSubscribeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, pk=kwargs.get('user_pk'))
        response = {}

        try:
            subscription = Subscription.objects.get(subscriber=self.request.user, subscribed_to=user)
            subscription.delete()
            response['is_subscribed'] = False
        except Subscription.DoesNotExist:
            Subscription.objects.create(subscriber=self.request.user, subscribed_to=user)
            response['is_subscribed'] = True

        response['total_subscribers'] = len(user.subscribers.all())
        return JsonResponse(response)

instagram/users/views/user_views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.apps import apps
from django.views.generic import DetailView, UpdateView, View

from ..forms import UserEditForm, UserPasswordChangeForm, UserLoginForm, UserRegisterForm
from ..models import Subscription, User


class UserDetailView(DetailView):
    template_name = 'user/details.html'
    pk_url_kwarg = 'user_pk'
    model = User
    context_object_name = 'account'

    def get_context_data(self, **kwargs):
        Post = apps.get_model('publications', 'Post')
        posts = Post.objects.filter(author__pk=self.kwargs.get('user_pk'))
        kwargs['posts'] = posts
        kwargs['posts_count'] = len(posts)
        if self.request.user.is_authenticated:
            kwargs['is_subscribed'] = self._is_subscribed()
        return super().get_context_data(**kwargs)

    def _is_subscribed(self):
        user_id = self.kwargs.get('user_pk')
        try:
            Subscription.objects.get(subscriber=self.request.user.pk, subscribed_to=get_object_or_404(User, pk=user_id))
            return True
        except Subscription.DoesNotExist:
            return False


class UserEditView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user/edit.html'
    form_class = UserEditForm
    context_object_name = 'account'
    pk_url_kwarg = 'user_pk'

    def test_func(self):
        return self.request.user.pk == self.kwargs['user_pk']

    def get_success_url(self):
        return reverse('users:details', kwargs={'user_pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user/password_change.html'
    form_class = UserPasswordChangeForm
    context_object_name = 'account'
    pk_url_kwarg = 'user_pk'

    def test_func(self):
        return self.request.user.pk == self.kwargs['user_pk']

    def get_success_url(self):
        return reverse('users:login')


class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(request.META.get('HTTP_REFERER'))


def account_login_view(request):
    if request.method == 'POST':
        context = {
            'form': UserLoginForm(data=request.POST)
        }
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('publications:post_list')
        else:
            context['has_error'] = True
            return render(request, 'user/login.html', context=context)
    context = {
        'form': UserLoginForm()
    }
    return render(request, 'user/login.html', context=context)


def account_register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('publications:post_list')
        else:
            context = {
                'form': form,
                'has_error': True
            }
            return render(request, 'user/register.html', context=context)
    else:
        form = UserRegisterForm()
        context = {
            'form': form
        }
        return render(request, 'user/register.html', context=context)

instagram/users/templates/user/account_details.html
{% extends 'base.html' %}

{% block title %}
{{ account.username }}
{% endblock %}

{% block main %}
<div class="container account-container">
    <div class="account-wrapper">
        <div class="account-avatar-wrapper">
            <div class="account-avatar" {% if account.profile.avatar %}style="background-image: url({{ account.profile.avatar.url }})"{% endif %}></div>
        </div>
        <div class="account-info-wrapper">
            <div class="account-info-main">
                <span class="account-info-main-username">{{ account.username | slice:':16' }}</span>
                {% if user.pk == account.pk %}
                <div class="account-info-main-button-wrapper">
                    <a href="{% url 'accounts:edit' account.pk %}" class="account-info-main-button">Редактировать профиль</a>
                </div>
                <div class="account-info-main-settings">
                    <span class="account-info-main-settings-trigger"></span>
                    <nav class="account-info-main-settings-menu">
                        <a href="{% url 'accounts:password_change' account.pk %}" class="account-info-main-settings-menu-link-overlay">
                            <span class="account-info-main-settings-menu-item">Сменить пароль</span>
                        </a>
                        <a href="{% url 'accounts:logout' %}" class="account-info-main-settings-menu-link-overlay">
                            <span class="account-info-main-settings-menu-item">Выйти</span>
                        </a>
                    </nav>
                </div>
                {% endif %}
            </div>
            <div class="account-info-stats">
                <div class="account-info-stats-block">Публикации: <span class="bold-text">{% if account.profile.publications %}{{ account.profile.publications }}{% else %}0{% endif %}</span></div>
                <a href="#" class="account-info-stats-block">
                    <div>Подписчики: <span class="bold-text">{% if account.profile.subscribers %}{{ account.profile.subscribers }}{% else %}0{% endif %}</span></div>
                </a>
                <a href="#" class="account-info-stats-block">
                    <div>Подписки: <span class="bold-text">{% if account.profile.subscribes %}{{ account.profile.subscribes }}{% else %}0{% endif %}</span></div>
                </a>
            </div>
            <div class="account-info-description">
                {% if account.profile.status %}
                <span class="bold-text">{{ account.profile.status }}</span>
                <br>
                {% endif %}
                {% if account.email %}
                <span>{{ account.email }}</span>
                <br>
                {% endif %}
                {% if account.profile.description %}
                <span>{{ account.profile.description }}</span>
                <br>
                {% endif %}
                {% if account.profile.phone %}
                <span>{{ account.profile.phone }}</span>
                <br>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="account-posts-wrapper">
        <div class="account-posts-header">
            <div class="account-posts-header-item active"><span>Публикации</span></div>
        </div>
        <div class="account-posts-container">
            <!--            <div class="account-post-item">-->
            <!--                <a href="#">-->
            <!--                    <div class="account-post-item-overlay">-->
            <!--                        <div class="account-post-item-overlay-text">-->
            <!--                            <div class="account-post-item-overlay-block likes">10</div>-->
            <!--                            <div class="account-post-item-overlay-block comments">0</div>-->
            <!--                        </div>-->
            <!--                    </div>-->
            <!--                </a>-->
            <!--            </div>-->
            <div class="account-post-nothing">Нет постов для показа</div>
        </div>
    </div>
</div>
{% if user.pk == account.pk %}
{% include 'partials/_profile_settings_script.html' %}
{% endif %}
{% endblock %}

instagram/users/templates/user/details.html
{% extends 'base.html' %}

{% block title %}
{{ account.username }}
{% endblock %}

{% block main %}
<div class="container account-container">
    <div class="account-wrapper">
        <div class="account-avatar-wrapper">
            <div class="account-avatar" {% if account.avatar %}style="background-image: url({{ account.avatar.url }})"{% endif %}></div>
        </div>
        <div class="account-info-wrapper">
            <div class="account-info-main">
                <span class="account-info-main-username">{{ account.username | slice:':16' }}</span>
                {% if user.is_authenticated %}
                {% if user.pk == account.pk %}
                <div class="account-info-main-button-wrapper">
                    <a href="{% url 'users:edit' account.pk %}" class="account-info-main-button">Редактировать профиль</a>
                </div>
                <div class="account-info-main-settings">
                    <span class="account-info-main-settings-trigger"></span>
                    <nav class="account-info-main-settings-menu">
                        <a href="{% url 'users:password_change' account.pk %}" class="account-info-main-settings-menu-link-overlay">
                            <span class="account-info-main-settings-menu-item">Сменить пароль</span>
                        </a>
                        <a href="{% url 'users:logout' %}" class="account-info-main-settings-menu-link-overlay">
                            <span class="account-info-main-settings-menu-item">Выйти</span>
                        </a>
                    </nav>
                </div>
                {% else %}
                <div class="account-info-main-button-wrapper">
                    <a href="{% url 'users:subscribe' account.pk %}" class="account-info-main-button subscribe">{% if is_subscribed %}Отписаться{% else %}Подписаться{% endif %}</a>
                </div>
                {% endif %}
                {% endif %}
            </div>
            <div class="account-info-stats">
                <div class="account-info-stats-block">Публикации: <span class="bold-text">{{ posts_count }}</span></div>
                <a href="#" class="account-info-stats-block">
                    <div>Подписчики: <span class="bold-text" id="subscribers-counter">{{ account.subscribers.all | length }}</span></div>
                </a>
                <a href="#" class="account-info-stats-block">
                    <div>Подписки: <span class="bold-text">{{ account.subscriptions.all | length }}</span></div>
                </a>
            </div>
            <div class="account-info-description">
                <span class="bold-text">{% if account.status %}{{ account.status }}{% else %}Без статуса{% endif %}</span>
                <br>
                {% if account.email %}
                <span>{{ account.email }}</span>
                <br>
                {% endif %}
                {% if account.description %}
                <span>{{ account.profile.description }}</span>
                <br>
                {% endif %}
                {% if account.phone %}
                <span>{{ account.profile.phone }}</span>
                <br>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="account-posts-wrapper">
        <div class="account-posts-header">
            <div class="account-posts-header-item active"><span>Публикации</span></div>
        </div>
        <div class="account-posts-container">
            {% for post in posts %}
            <div class="account-post-item" style="background-image: url({{ post.image.url }});">
                <a href="{% url 'publications:post_detail' post.pk %}">
                    <div class="account-post-item-overlay">
                        <div class="account-post-item-overlay-text">
                            <div class="account-post-item-overlay-block likes">{{ post.likes.all | length }}</div>
                            <div class="account-post-item-overlay-block comments">{{ post.comments.all | length }}</div>
                        </div>
                    </div>
                </a>
            </div>
            {% empty %}
            <div class="account-post-nothing">Нет постов для показа</div>
            {% endfor %}
        </div>
    </div>
</div>
{% include 'partials/_subscribe_script.html' %}
{% if user.pk == account.pk %}
{% include 'partials/_profile_menu_script.html' %}
{% endif %}
{% endblock %}

instagram/users/templates/user/edit.html
{% extends 'base.html' %}

{% block title %}
Edit
{% endblock %}

{% block main %}
<div class="container register-container">
    <div class="register-wrapper">
        <form action="{% url 'users:edit' account.pk %}" method="post" class="form logo" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'partials/_form.html' %}
            <div class="form-group">
                <button type="submit" class="button-submit">Сохранить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

instagram/users/templates/user/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block main %}
<div class="container register-container">
    <div class="register-wrapper">
        <form action="{% url 'users:login' %}" method="post" class="form logo">
            {% csrf_token %}
            {% include 'partials/_form.html' %}
            <div class="form-group">
                <button type="submit" class="button-submit">Авторизоваться</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

instagram/users/templates/user/password_change.html
{% extends 'base.html' %}

{% block title %}
Password change
{% endblock %}

{% block main %}
<div class="container register-container">
    <div class="register-wrapper">
        <form action="{% url 'users:password_change' account.pk %}" method="post" class="form logo">
            {% csrf_token %}
            {% include 'partials/_form.html' %}
            <div class="form-group">
                <button type="submit" class="button-submit">Сменить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

instagram/users/templates/user/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}

{% block main %}
<div class="container register-container">
    <div class="register-wrapper">
        <form action="{% url 'users:register' %}" method="post" class="form logo">
            {% csrf_token %}
            {% include 'partials/_form.html' %}
            <div class="form-group">
                <button type="submit" class="button-submit">Зарегистрироваться</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}