instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('publications.urls', namespace='publications')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/publications/urls.py
from django.urls import path
from .views import PostListView, PostDeleteView, PostEditView, PostDetailView, CommentCreateView, LikeView, \
    PostCreateView, CommentDeleteView

app_name = 'publications'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('posts/<int:post_pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('posts/<int:post_pk>/edit/', PostEditView.as_view(), name='post_edit'),
    path('posts/<int:post_pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/<int:post_pk>/comment/', CommentCreateView.as_view(), name='comment_create'),
    path('posts/<int:post_pk>/like/', LikeView.as_view(), name='like'),
    path('posts/new/', PostCreateView.as_view(), name='post_create'),
    path('comments/<int:comment_pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
]

instagram/users/urls.py
from django.urls import path
from .views import UserDetailView, UserEditView, UserSubscribeView, UserPasswordChangeView, UserLogoutView, \
    account_register_view, account_login_view


app_name = 'users'

urlpatterns = [
    path('<int:user_pk>/', UserDetailView.as_view(), name='details'),
    path('<int:user_pk>/edit/', UserEditView.as_view(), name='edit'),
    path('<int:user_pk>/subscribe/', UserSubscribeView.as_view(), name='subscribe'),
    path('<int:user_pk>/password_change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', account_register_view, name='register'),
    path('login/', account_login_view, name='login'),
]

instagram/publications/models.py
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(
        'users.User',
        related_name='posts',
        on_delete=models.CASCADE,
        verbose_name='Автор',
        null=False,
        blank=False,
        default=None
    )
    image = models.ImageField(
        null=False,
        blank=False,
        upload_to='post_pics',
        verbose_name='Картинка'
    )
    text = models.TextField(
        max_length=500,
        verbose_name='Текст',
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        null=True,
        blank=True
    )

    def __str__(self):
        text = ' '.join(self.text.split(' ')[:4])
        return f'{self.author.username} - {text}...'


class Comment(models.Model):
    author = models.ForeignKey(
        'users.User',
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Автор',
        null=False,
        blank=False,
        default=None
    )
    post = models.ForeignKey(
        'publications.Post',
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Пост',
        null=False,
        blank=False,
        default=None
    )
    text = models.TextField(
        verbose_name='Текст',
        null=False,
        blank=False,
        default=None,
        max_length=100
    )
    created_at = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        null=True,
        blank=True
    )

    def __str__(self):
        text = ' '.join(self.text.split(' ')[:4])
        return f'{self.post.pk} - {self.author.username} - {text}'


class Like(models.Model):
    user = models.ForeignKey(
        'users.User',
        related_name='likes',
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        null=False,
        blank=False,
        default=None
    )
    post = models.ForeignKey(
        'publications.Post',
        related_name='likes',
        on_delete=models.CASCADE,
        verbose_name='Пост',
        null=False,
        blank=False,
        default=None
    )

    def __str__(self):
        return f'{self.user.username} понравился пост {self.post}'

instagram/publications/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author']

instagram/publications/views/comment_views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import View
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse

from ..models import Post, Comment


class CommentCreateView(View):
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs.get('post_pk'))

        comment = Comment()
        comment.author = self.request.user
        comment.post = post
        comment.text = self.request.POST.get('text')
        comment.save()

        return redirect(reverse('publications:post_detail', kwargs={'post_pk': kwargs.get('post_pk')}))


class CommentDeleteView(UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs.get('comment_pk'))
        comment.delete()
        return redirect(request.META.get('HTTP_REFERER'))

    def test_func(self):
        comment = get_object_or_404(Comment, pk=self.kwargs.get('comment_pk'))
        return self.request.user.pk == comment.author.pk

instagram/publications/views/like_views.py
from django.views.generic import View
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from ..models import Post, Like


class LikeView(View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs.get('post_pk'))
        response = {}

        try:
            like = Like.objects.get(post=post, user=self.request.user)
            like.delete()
            response['is_liked'] = False
        except Like.DoesNotExist:
            Like.objects.create(post=post, user=self.request.user)
            response['is_liked'] = True

        response['total_likes'] = len(post.likes.all())

        return JsonResponse(response)

instagram/publications/views/post_views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, View, CreateView, UpdateView, DetailView
from django.apps import apps
from random import randint

from ..models import Comment, Post
from ..forms import PostForm


class PostListView(ListView):
    template_name = 'post/list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        subscribed_users = self._get_subscribed_users()

        if self.request.user.is_authenticated:
            subscribed_users_posts = Post.objects.filter(author__pk__in=subscribed_users)
            posts_of_current_user = Post.objects.filter(author__pk=self.request.user.pk)
            return (subscribed_users_posts | posts_of_current_user).order_by('-created_at')
        else:
            return Post.objects.all().order_by('-created_at')

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            kwargs['recommended_users'] = self._get_recommended_users()
            kwargs['liked_posts'] = self._get_liked_posts()
            kwargs['subscribed_users'] = self._get_subscribed_users()
        return super().get_context_data(**kwargs)

    def _get_subscribed_users(self):
        Subscription = apps.get_model('users', 'Subscription')
        subscriptions = Subscription.objects.filter(subscriber__pk=self.request.user.pk)
        subscribed_users = []
        for subscription in subscriptions:
            subscribed_users.append(subscription.subscribed_to.pk)
        return subscribed_users

    def _get_liked_posts(self):
        User = apps.get_model('users', 'User')
        liked_posts = []
        likes = get_object_or_404(User, pk=self.request.user.pk).likes.all()
        for like in likes:
            liked_posts.append(like.post.pk)
        return liked_posts

    def _get_recommended_users(self):
        recommended_users_needed = 3  # Сколько пользователей нужно показать
        recommended_users = []
        User = apps.get_model('users', 'User')
        users = User.objects.all()
        max_user_index = len(users)

        # Если пользователей меньше, чем нужно, то выведи сколько есть
        if (max_user_index - 1) < recommended_users_needed:
            recommended_users_needed = max_user_index - 1

        recommended_user_count = 0
        already_added_indexes = []

        while True:
            # Если пользователей уже достаточно
            if recommended_user_count == recommended_users_needed:
                break
            random_index = randint(1, max_user_index)

            # Не добавляй меня и уже добавленных пользователей
            if random_index == self.request.user.pk or random_index in already_added_indexes:
                continue

            already_added_indexes.append(random_index)
            try:
                recommended_users.append(User.objects.get(pk=random_index))
            except User.DoesNotExist:
                continue
            recommended_user_count += 1

        return recommended_users


class PostDeleteView(UserPassesTestMixin, View):
    def get(self, request, *args, **kwargs):
        post_id = kwargs.get('post_pk')
        post = get_object_or_404(Post, pk=post_id)
        post.delete()
        return redirect('publications:post_list')

    def test_func(self):
        post_id = self.kwargs.get('post_pk')
        post = get_object_or_404(Post, pk=post_id)
        return self.request.user.pk == post.author.pk


class PostCreateView(CreateView):
    template_name = 'post/create.html'
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('publications:post_list')


class PostEditView(UserPassesTestMixin, UpdateView):
    template_name = 'post/edit.html'
    model = Post
    form_class = PostForm
    pk_url_kwarg = 'post_pk'

    def get_success_url(self):
        return reverse('publications:post_list')

    def test_func(self):
        post_id = self.kwargs.get('post_pk')
        post = get_object_or_404(Post, pk=post_id)
        return self.request.user.pk == post.author.pk


class PostDetailView(DetailView):
    template_name = 'post/detail.html'
    pk_url_kwarg = 'post_pk'

    def get_queryset(self):
        return Post.objects.all()

    def get_context_data(self, **kwargs):
        kwargs['comments'] = Comment.objects.filter(post__pk=self.kwargs.get('post_pk')).order_by('created_at')
        if self.request.user.is_authenticated:
            kwargs['liked_posts'] = self._get_liked_posts()
        return super().get_context_data(**kwargs)

    def _get_liked_posts(self):
        User = apps.get_model('users', 'User')
        liked_posts = []
        likes = get_object_or_404(User, pk=self.request.user.pk).likes.all()
        for like in likes:
            liked_posts.append(like.post.pk)
        return liked_posts

instagram/publications/templates/post/create.html
{% extends 'base.html' %}

{% block title %}
Create
{% endblock %}

{% block main %}
<div class="container register-container">
    <div class="register-wrapper">
        <form action="{% url 'publications:post_create' %}" method="post" class="form logo" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'partials/_form.html' %}
            <div class="form-group">
                <button type="submit" class="button-submit">Опубликовать</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

instagram/publications/templates/post/detail.html
{% extends 'base.html' %}

{% block title %}
Instagram
{% endblock %}

{% block main %}
<div class="container main-container detail-container">
    <div class="post-detail-wrapper">
        <div class="post-detail-image-wrapper">
            <div class="post-detail-image-blur-overlay" style="background-image: url({{ post.image.url }});"></div>
            <img src="{{ post.image.url }}" alt="post-image" class="post-detail-image">
        </div>
        <aside class="post-detail">
            <div class="post-detail-header">
                <div class="post-detail-header-author">
                    <a href="{% url 'users:details' post.author.pk %}">
                        <div class="post-detail-header-author-avatar-wrapper">
                            <div class="post-detail-header-author-avatar" {% if post.author.avatar %}style="background-image: url({{ post.author.avatar.url }});"{% endif %}></div>
                        </div>
                    </a>
                    <a href="{% url 'users:details' post.author.pk %}">
                        <span class="post-detail-header-author-username">{{ post.author.username }}</span>
                    </a>
                </div>
                <div class="post-item-header-menu-trigger-wrapper">
                    <div class="post-item-header-menu-wrapper" id="post-item-header-menu-wrapper_1">
                        <span class="post-item-header-menu-trigger" id="post-item-header-menu-trigger_1"></span>
                        <nav class="post-item-header-menu">
                            <a href="{% url 'users:details' post.author.pk %}" class="post-item-header-menu-link-overlay">
                                <span class="post-item-header-menu-item">Перейти к автору</span>
                            </a>
                            {% if user.pk == post.author.pk %}
                            <a href="{% url 'publications:post_edit' post.pk %}" class="post-item-header-menu-link-overlay">
                                <span class="post-item-header-menu-item">Редактировать</span>
                            </a>
                            <a href="{% url 'publications:post_delete' post.pk %}" class="post-item-header-menu-link-overlay">
                                <span class="post-item-header-menu-item delete-text">Удалить</span>
                            </a>
                            {% endif %}
                        </nav>
                    </div>
                </div>
            </div>
            {% if post.text %}
            <div class="post-item-text-wrapper">
                <p class="post-item-text"><a href="{% url 'users:details' post.author.pk %}"><span class="post-item-comment-username">{{ post.author.username }}</span></a> {{ post.text }}</p>
            </div>
            {% endif %}
            <div class="post-detail-comment-container">
                {% for comment in comments %}
                <div class="post-item-comment">
                    <span class="post-item-comment-username"><a href="{% url 'users:details' comment.author.pk %}">{{ comment.author.username }}</a></span>
                    <span class="post-item-comment-text">{{ comment.text }}</span>
                    <div class="post-item-comment-control-block">
                        <span>{{ comment.created_at | date:'H:i d.m.Y' }}</span>
                        {% if user.pk == comment.author.pk %}
                        <a class="delete-text" href="{% url 'publications:comment_delete' comment.pk %}">Удалить</a>
                        {% endif %}
                    </div>
                </div>
                {% empty %}
                <div class="account-post-nothing">Нет комментариев для показа</div>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <div class="post-item-button-wrapper">
                <div class="post-item-button-wrapper-left">
                    <a href="{% url 'publications:like' post.pk %}" id="like_button-{{ post.pk }}" class="post-item-button like-button {% if post.pk in liked_posts %}active{% endif %}">
                        <span class="post-item-button-icon like"></span>
                    </a>
                </div>
            </div>
            {% endif %}
            <div class="post-item-like-counter">
                <span class="post-item-like-counter-text" id="like_counter-{{ post.pk }}">{% if post.likes.all %}{{ post.likes.all | length }}{% else %}Нет{% endif %} отметок "Нравится"</span>
            </div>
            {% if user.is_authenticated %}
            <div class="post-item-comment-create">
                <form action="{% url 'publications:comment_create' post.pk %}" method="post" class="post-item-comment-create-form">
                    {% csrf_token %}
                    <input name="text" type="text" class="post-item-comment-create-input" placeholder="Добавьте комментарий...">
                    <div class="post-item-comment-submit-wrapper">
                        <button type="submit" class="post-item-comment-submit">Опубликовать</button>
                    </div>
                </form>
            </div>
            {% endif %}
        </aside>
    </div>
</div>
{% include 'partials/_like_script.html' %}
{% include 'partials/_post_menu_script.html' %}
{% endblock %}

instagram/publications/templates/post/edit.html
{% extends 'base.html' %}

{% block title %}
Edit
{% endblock %}

{% block main %}
<div class="container register-container">
    <div class="register-wrapper">
        <form action="{% url 'publications:post_edit' post.pk %}" method="post" class="form logo" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'partials/_form.html' %}
            <div class="form-group">
                <button type="submit" class="button-submit">Сохранить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

instagram/publications/templates/post/list.html
{% extends 'base.html' %}

{% block title %}
Instagram
{% endblock %}

{% block main %}
<div class="container main-container">
    <section class="posts-container">
        {% for post in posts %}
        <div class="post-item">
            <div class="post-item-header">
                <div class="post-item-header-account">
                    <div class="post-item-header-account-overlay">
                        <a href="{% url 'users:details' post.author.pk %}" class="post-item-header-account-link-overlay">
                            <div class="post-item-header-account-avatar-wrapper">
                                <div class="post-item-header-account-avatar" {% if post.author.avatar %}style="background-image: url({{ post.author.avatar.url }})"{% endif %}></div>
                            </div>
                            <div class="post-item-header-account-username">{{ post.author.username }}</div>
                        </a>
                    </div>
                </div>
                <div class="post-item-header-menu-trigger-wrapper">
                    <div class="post-item-header-menu-wrapper" id="post-item-header-menu-wrapper_{{ post.pk }}">
                        <span class="post-item-header-menu-trigger" id="post-item-header-menu-trigger_{{ post.pk }}"></span>
                        <nav class="post-item-header-menu">
                            <a href="{% url 'publications:post_detail' post.pk %}" class="post-item-header-menu-link-overlay">
                                <span class="post-item-header-menu-item">Открыть</span>
                            </a>
                            <a href="{% url 'users:details' post.author.pk %}" class="post-item-header-menu-link-overlay">
                                <span class="post-item-header-menu-item">Перейти к автору</span>
                            </a>
                            {% if user.pk == post.author.pk %}
                            <a href="{% url 'publications:post_edit' post.pk %}" class="post-item-header-menu-link-overlay">
                                <span class="post-item-header-menu-item">Редактировать</span>
                            </a>
                            <a href="{% url 'publications:post_delete' post.pk %}" class="post-item-header-menu-link-overlay">
                                <span class="post-item-header-menu-item delete-text">Удалить</span>
                            </a>
                            {% endif %}
                        </nav>
                    </div>
                </div>
            </div>
            <div class="post-item-image-wrapper">
                <a href="{% url 'publications:post_detail' post.pk %}">
                    <img src="{{ post.image.url }}" alt="#" class="post-item-image">
                </a>
            </div>
            {% if user.is_authenticated %}
            <div class="post-item-button-wrapper">
                <div class="post-item-button-wrapper-left">
                    <a href="{% url 'publications:like' post.pk %}" id="like_button-{{ post.pk }}" class="post-item-button like-button {% if post.pk in liked_posts %}active    {% endif %}">
                        <span class="post-item-button-icon like"></span>
                    </a>
                </div>
            </div>
            {% endif %}
            <div class="post-item-like-counter">
                <span class="post-item-like-counter-text" id="like_counter-{{ post.pk }}">{% if post.likes.all %}{{ post.likes.all | length }}{% else %}Нет{% endif %} отметок "Нравится"</span>
            </div>
            {% if post.text %}
            <div class="post-item-text-wrapper">
                <p class="post-item-text"><a href="{% url 'users:details' post.author.pk %}"><span class="post-item-comment-username">{{ post.author.username }}</span></a> {{ post.text }}</p>
            </div>
            {% endif %}
            <div class="post-item-comment-container">
                {% for comment in post.comments.all %}
                <div class="post-item-comment">
                    <span class="post-item-comment-username"><a href="{% url 'users:details' comment.author.pk %}">{{ comment.author.username }}</a></span>
                    <span class="post-item-comment-text">{{ comment.text }}</span>
                    <div class="post-item-comment-control-block">
                        <span>{{ comment.created_at | date:'H:i d.m.Y' }}</span>
                        {% if user.pk == comment.author.pk %}
                        <a class="delete-text" href="{% url 'publications:comment_delete' comment.pk %}">Удалить</a>
                        {% endif %}
                    </div>
                </div>
                {% empty %}
                <div class="account-post-nothing">Нет комментариев для показа</div>
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <div class="post-item-comment-create">
                <form action="{% url 'publications:comment_create' post.pk %}" method="post" class="post-item-comment-create-form">
                    {% csrf_token %}
                    <input name="text" type="text" class="post-item-comment-create-input" placeholder="Добавьте комментарий...">
                    <div class="post-item-comment-submit-wrapper">
                        <button type="submit" class="post-item-comment-submit">Опубликовать</button>
                    </div>
                </form>
            </div>
            {% endif %}
        </div>
        {% empty %}
        <div class="account-post-nothing">Нет постов для показа</div>
        {% endfor %}
    </section>
    <aside class="sidebar">
        <div class="sidebar-account-wrapper">
            <div class="sidebar-account-block">
                {% if user.is_authenticated %}
                <a href="{% url 'users:details' user.pk %}">
                    <div class="sidebar-account-avatar" {% if user.avatar %}style="background-image: url({{ user.avatar.url }});"{% endif %}></div>
                </a>
                {% else %}
                <div class="sidebar-account-avatar"></div>
                {% endif %}
                <div class="sidebar-account-text">
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:details' user.pk %}">
                        <span class="sidebar-account-username">{{ user.username }}</span>
                    </a>
                    <span class="sidebar-account-status">{% if user.status %}{{ user.status }}{% else %}Без статуса{% endif %}</span>
                    {% else %}
                    <span class="sidebar-account-username">Аноним</span>
                    <span class="sidebar-account-status">Аноним</span>
                    {% endif %}
                </div>
            </div>
            {% if user.is_authenticated %}
            <a href="{% url 'publications:post_create' %}" class="post-create-link">Добавить<br>публикацию</a>
            {% endif %}
        </div>
        <div class="sidebar-recommendation">
            <div class="sidebar-recommendation-header">
                <span class="sidebar-recommendation-header-heading">Рекомендации для вас</span>
                <a href="#" class="sidebar-recommendation-header-link">Все</a>
            </div>
            <div class="sidebar-recommendation-account-container">
                {% for user in recommended_users %}
                <div class="sidebar-recommendation-account">
                    <div class="sidebar-recommendation-account-wrapper">
                        <a href="{% url 'users:details' user.pk %}">
                            <div class="sidebar-recommendation-account-avatar-wrapper">
                                <div class="sidebar-recommendation-account-avatar" {% if user.avatar %}style="background-image: url({{ user.avatar.url }});"{% endif %}></div>
                            </div>
                        </a>
                        <div class="sidebar-recommendation-account-text">
                            <a href="{% url 'users:details' user.pk %}">
                                <span class="sidebar-recommendation-account-text-username">{{ user.username }}</span>
                            </a>
                            <span class="sidebar-recommendation-account-text-status">{% if user.status %}{{ user.status }}{% else %}Без статуса{% endif %}</span>
                        </div>
                    </div>
                    <div class="sidebar-recommendation-account-button-wrapper">
                        <a href="{% url 'users:subscribe' user.pk %}" class="sidebar-recommendation-account-button">{% if user.pk in subscribed_users %}Отписаться{% else %}Подписаться{% endif %}</a>
                    </div>
                </div>
                {% empty %}
                <div class="account-post-nothing">Нет рекомендованных пользователей</div>
                {% endfor %}
            </div>
        </div>
    </aside>
</div>
{% include 'partials/_recommendation_subscribe_script.html' %}
{% include 'partials/_like_script.html' %}
{% include 'partials/_post_menu_script.html' %}
{% endblock %}